name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Build Site
      run: npm run build
    - name: Set up S3cmd cli tool
      uses: s3-actions/s3cmd@v1.4.0
      with:
        provider: linode
        region: "us-east-1"
        access_key: ${{ secrets.S3_ACCESS_KEY }}
        secret_key: ${{ secrets.S3_SECRET_KEY }}
    - name: Push files to Object Storage
      run: |
        s3cmd sync build s3://bucket-personal-site
